version: "3.8"

services:
    app:
        container_name: webapp
        build:
            dockerfile: ./dockerfile
            context: .
            target: app
        ports:
            - 3000:3000
        command: [ "npm", "run", "start" ]
    
    pw-runner:
        build:
            dockerfile: ./dockerfile
            context: .
            target: pw-runner
        volumes:
            - ./tests/example.spec.ts-snapshots:/src/tests/example.spec.ts-snapshots
            - ./test-results:/src/test-results
        command: [ "npm", "run", "test" ]

    pw-server:
        build:
            dockerfile: ./dockerfile
            context: .
            target: pw-server
        ports:
            - 1010:1010
            - 1011:1011
            - 1012:1012
        extra_hosts:
            - "host.docker.internal:host-gateway"
